capitals = {'India': {'Capital': 'New Delhi', 'States': 
                      {'Maharashtra': 'Mumbai', 'Karnataka': 'Bengaluru', 'Tamil Nadu': 'Chennai', 'West Bengal': 'Kolkata', 'Uttar Pradesh': 'Lucknow'}}, 
                      'China': {'Capital': 'Beijing', 'States': {'Guangdong': 'Guangzhou', 'Shandong': 'Jinan', 'Henan': 'Zhengzhou', 'Sichuan': 'Chengdu', 'Jiangsu': 'Nanjing'}}, 
                      'Japan': {'Capital': 'Tokyo', 'States': {'Hokkaido': 'Sapporo', 'Osaka': 'Osaka', 'Kyoto': 'Kyoto', 'Fukuoka': 'Fukuoka', 'Aichi': 'Nagoya'}}, 
                      'Russia': {'Capital': 'Moscow', 'States': {'Moscow Oblast': 'Moscow', 'Saint Petersburg': 'Saint Petersburg', 'Novosibirsk': 'Novosibirsk', 'Yekaterinburg': 'Yekaterinburg', 'Kazan': 'Kazan'}},
                      'Saudi Arabia': {'Capital': 'Riyadh', 'States': {'Makkah': 'Mecca', 'Madinah': 'Medina', 'Eastern Province': 'Dammam', 'Riyadh': 'Riyadh', 'Assir': 'Abha'}}, 
                      'United Kingdom': {'Capital': 'London', 'States': {'England': 'London', 'Scotland': 'Edinburgh', 'Wales': 'Cardiff', 'Northern Ireland': 'Belfast'}}, 
                      'Germany': {'Capital': 'Berlin', 'States': {'Bavaria': 'Munich', 'North Rhine-Westphalia': 'Düsseldorf', 'Baden-Württemberg': 'Stuttgart', 'Lower Saxony': 'Hanover', 'Hesse': 'Wiesbaden'}}, 
                      'France': {'Capital': 'Paris', 'States': {'Île-de-France': 'Paris', "Provence-Alpes-Côte d'Azur": 'Marseille', 'Occitanie': 'Toulouse', 'Nouvelle-Aquitaine': 'Bordeaux', 'Grand Est': 'Strasbourg'}}, 
                      'Italy': {'Capital': 'Rome', 'States': {'Lazio': 'Rome', 'Lombardy': 'Milan', 'Campania': 'Naples', 'Sicily': 'Palermo', 'Veneto': 'Venice'}}, 
                      'Spain': {'Capital': 'Madrid', 'States': {'Andalusia': 'Seville', 'Catalonia': 'Barcelona', 'Madrid': 'Madrid', 'Valencia': 'Valencia', 'Galicia': 'Santiago de Compostela'}},
                      'United States': {'Capital': 'Washington, D.C.', 'States': {'California': 'Sacramento', 'Texas': 'Austin', 'Florida': 'Tallahassee', 'New York': 'Albany', 'Illinois': 'Springfield'}}, 
                      'Canada': {'Capital': 'Ottawa', 'States': {'Ontario': 'Toronto', 'Quebec': 'Quebec City', 'British Columbia': 'Victoria', 'Alberta': 'Edmonton', 'Manitoba': 'Winnipeg'}}, 
                      'Mexico': {'Capital': 'Mexico City', 'States': {'Jalisco': 'Guadalajara', 'Nuevo León': 'Monterrey', 'Puebla': 'Puebla', 'Veracruz': 'Xalapa', 'Guanajuato': 'Guanajuato'}}, 
                      'Brazil': {'Capital': 'Brasília', 'States': {'São Paulo': 'São Paulo', 'Rio de Janeiro': 'Rio de Janeiro', 'Minas Gerais': 'Belo Horizonte', 'Bahia': 'Salvador', 'Paraná': 'Curitiba'}}, 
                      'Argentina': {'Capital': 'Buenos Aires', 'States': {'Buenos Aires': 'La Plata', 'Córdoba': 'Córdoba', 'Santa Fe': 'Santa Fe', 'Mendoza': 'Mendoza', 'Tucumán': 'San Miguel de Tucumán'}}, 
                      'Chile': {'Capital': 'Santiago', 'States': {'Valparaíso': 'Valparaíso', 'Maule': 'Talca', 'Biobío': 'Concepción', 'Coquimbo': 'La Serena', 'Los Lagos': 'Puerto Montt'}}, 
                      'Australia': {'Capital': 'Canberra', 'States': {'New South Wales': 'Sydney', 'Victoria': 'Melbourne', 'Queensland': 'Brisbane', 'Western Australia': 'Perth', 'South Australia': 'Adelaide'}}, 
                      'New Zealand': {'Capital': 'Wellington', 'States': {'Auckland': 'Auckland', 'Canterbury': 'Christchurch', 'Wellington': 'Wellington', 'Otago': 'Dunedin', 'Waikato': 'Hamilton'}}}
